version: '3'

services:
  mongo:
    image: mongo
    # container_name: photo-mongo
    # hostname: photo-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database:/data/db

  node:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: .docker/node/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    ports:
      - "80:80"

volumes:
  database:
